name: Run tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4, 8.3]

    container: ghcr.io/bulkgate/plugin:${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run tester

      - name: Run phpstan
        run: composer run phpstan

  coverage:
    runs-on: ubuntu-latest

    container: ghcr.io/bulkgate/plugin:8.3

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html